### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by RichardLitt** [NREL/WETOStack#5]
Is there a license for this code? I'm not seeing it as a top-level doc.

**Comment by rafmudaf** [comment]
I admittedly overlooked licensing this repository since the primary product is a website generated by Jupyter Book. After this issue was raised, the NREL legal team and I decided that the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International license is appropriate here. There license file has been added to the repository and the generated website reflects the license, as well.

Thanks for pointing this out @RichardLitt.

**Comment by RichardLitt** [comment]
Thank you!
